version: '3'
services:
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        - USERNAME=${USER}
    command: sleep infinity
    container_name: app
    tty: true
    volumes:
      - vscode-extension-volume:/root/.vscode-server/extensions
      - ../..:/workspaces:delegated
volumes:
  vscode-extension-volume: {}