version: '3'
services:
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    container_name: app
    tty: true
    volumes:
      - ../..:/workspaces